
language: python
python:
    - "2.7"
install:
    - pip install -r requirements.txt
    - pip install coveralls
before_install:
    - sudo apt-get update
    - sudo apt-get build-dep python-pygame
    - sudo apt-get install mercurial
script:
    - nosetests tests/unittests.py
    - coverage run --source=tests/unittests.py run.py test
after_success:
  coveralls
    
